// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXcFdWs_5SRQt-VraTaSyIOr3Odh444_g',
    appId: '1:26123631594:web:adc1fc0c1edb384a7d9093',
    messagingSenderId: '26123631594',
    projectId: 'panda-hub-project',
    authDomain: 'panda-hub-project.firebaseapp.com',
    storageBucket: 'panda-hub-project.appspot.com',
    measurementId: 'G-GL09YNJ5LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvmfyYq8OrHVQjhqb1Urkd6vrH9XejcyY',
    appId: '1:26123631594:android:f9981f0596350da57d9093',
    messagingSenderId: '26123631594',
    projectId: 'panda-hub-project',
    storageBucket: 'panda-hub-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS-yJNfrzJXppgml2-Ra5j-qjgwENIako',
    appId: '1:26123631594:ios:5af24a1ea4bce5417d9093',
    messagingSenderId: '26123631594',
    projectId: 'panda-hub-project',
    storageBucket: 'panda-hub-project.appspot.com',
    iosBundleId: 'com.example.pandaHubFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS-yJNfrzJXppgml2-Ra5j-qjgwENIako',
    appId: '1:26123631594:ios:5af24a1ea4bce5417d9093',
    messagingSenderId: '26123631594',
    projectId: 'panda-hub-project',
    storageBucket: 'panda-hub-project.appspot.com',
    iosBundleId: 'com.example.pandaHubFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXcFdWs_5SRQt-VraTaSyIOr3Odh444_g',
    appId: '1:26123631594:web:895d492a023d25677d9093',
    messagingSenderId: '26123631594',
    projectId: 'panda-hub-project',
    authDomain: 'panda-hub-project.firebaseapp.com',
    storageBucket: 'panda-hub-project.appspot.com',
    measurementId: 'G-R9998NG0W9',
  );
}
